### ISSUE TITLE
How to add a non-schema directive?

### ISSUE THREAD

**Issue by bsara** [graphql-java-kickstart/graphql-java-tools#246]
I've read the issue and everything about how to add a schema directive:

But what I need to know is how to add a non-schema directive (I.E. for a query, mutation, etc.).

I am supposed to be able to define a directive like this:

```graphql
directive @hasAccess(permission: [Permission!]!) on
    QUERY
  | MUTATION
  | SUBSCRIPTION
  | FIELD
```

But what do I need to create/do on the Java side for that to be registered in the `SchemaParser`? Is this even possible right now with this library?

**Comment by bsara** [comment]
@oliemansm just seeing if this question can get some love. :smiley:

**Comment by bsara** [comment]
I've started work on implementing the parsing and automatic creation of custom directives. However, I could use help with the validation piece that is needed here.

Here are my current changes: bsara/graphql-java-tools@309ecdcb98ec4831e9f9799929a146f32d0e3dfc
And here is where I assume that validation needs to take place: https://github.com/bsara/graphql-java-tools/blob/309ecdcb98ec4831e9f9799929a146f32d0e3dfc/src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt#L89

**Comment by oliemansm** [comment]
@bsara I've got another project that I have to give priority atm, will try to take a look at this somewhere in between as soon as I can.

**Comment by bsara** [comment]
@oliemansm no worries, I completely understand. sorry if I put undue pressure on you.

**Comment by alexgenco** [comment]
Wanted to bump this as well, we have a use case for a `FIELD` directive, and it looks like graphql-java supports this, but graphql-java-tools doesn't seem to be registering it. We have both the `directive` declaration in the schema, and we are registering a `SchemaDirectiveWiring` with the `SchemaParser`. However we are getting `Validation error of type UnknownDirective` in our response when we include the directive in the query.

**Comment by oliemansm** [comment]
I've updated the sample to show how to use directives on field and argument level here: https://github.com/graphql-java-kickstart/samples/tree/master/directives. You should be able to use the other types of directives similarly. Does this help?

**Comment by alexgenco** [comment]
@oliemansm those examples are of schema directives, which are working fine for us. We (and I think the OP) were asking specifically about directives used in the query.

We worked around this by adding an `additionalDirective` to the `GraphQLSchema` object after building it with `makeExecutableSchema`. This seems to bypass the `SchemaDirectiveWiring` functionality, since that interface doesn't provide a hook for the `FIELD` directive location, only `FIELD_DEFINITION` (`onField`). So we instead are using an instrumentation to check for the presence of the directive when resolving fields.

It would be nice to allow registering query directives in a similar way to schema directives. Something like a `QueryDirectiveWiring` interface and a corresponding `SchemaParser#directive` method to register it. That seems like it would require both graphql-java-tools and graphql-java buy-in though 🤷‍♂

**Comment by bsara** [comment]
@alexgreco is correct, we are looking for directives that can be used by a client in their queries, not those used in the schema.

**Comment by bsara** [comment]
I've tried to implement what @alexgreco had suggested in allowing registration to work like schema directives are registered; I just don't now the codebase well enough to finish off the implementation with my current time constraints.

If someone could help me with the implementation that I've referenced in my previous comments, that would be awesome.

**Comment by cliedeman** [comment]
I think this is solved by https://github.com/graphql-java-kickstart/graphql-java-tools/pull/312. I used this to integrate https://github.com/bbakerman/graphql-java-extended-validation. I think you could also build a permission constraint directive using that library

**Comment by vojtapol** [comment]
Solved by #312. Please comment if it did not solve your issue and we can reopen this.

**Comment by bsara** [comment]
@vojtapol I totally lost track of this ticket. No, that doesn't solve this issue. I was looking for a way for a client to place a directive in their query...much like `@if`, `@skip`, or `@delay`.

**Comment by luiznaac** [comment]
Hello everyone! I'm trying to achieve the same result, to create a directive to be used in a query. Are there any updates on this? @bsara
